# auto-generated by scripts/convert_gdmlpart.py
def construct_materials(geom):

    e_vacuum = geom.matter.Element("videRef", "VACUUM", 1, "1g/mole")
    e_cu = geom.matter.Element("copper", "Cu", 29, "63.546g/mole")
    e_be = geom.matter.Element("beryllium", "Be", 4, "9.0121831g/mole")
    e_br = geom.matter.Element("bromine", "Br", 35, "79.904g/mole")
    e_h = geom.matter.Element("hydrogen", "H", 1, "1.0079g/mole")
    e_n = geom.matter.Element("nitrogen", "N", 7, "14.0067g/mole")
    e_o = geom.matter.Element("oxygen", "O", 8, "15.999g/mole")
    e_al = geom.matter.Element("aluminum", "Al", 13, "26.9815g/mole")
    e_si = geom.matter.Element("silicon", "Si", 14, "28.0855g/mole")
    e_c = geom.matter.Element("carbon", "C", 6, "12.0107g/mole")
    e_k = geom.matter.Element("potassium", "K", 19, "39.0983g/mole")
    e_cr = geom.matter.Element("chromium", "Cr", 24, "51.9961g/mole")
    e_fe = geom.matter.Element("iron", "Fe", 26, "55.8450g/mole")
    e_ni = geom.matter.Element("nickel", "Ni", 28, "58.6934g/mole")
    e_ca = geom.matter.Element("calcium", "Ca", 20, "40.078g/mole")
    e_mg = geom.matter.Element("magnesium", "Mg", 12, "24.305g/mole")
    e_na = geom.matter.Element("sodium", "Na", 11, "22.99g/mole")
    e_ti = geom.matter.Element("titanium", "Ti", 22, "47.867g/mole")
    e_ar = geom.matter.Element("argon", "Ar", 18, "39.9480g/mole")
    e_s = geom.matter.Element("sulphur", "S", 16, "32.065g/mole")
    e_p = geom.matter.Element("phosphorus", "P", 15, "30.973g/mole")


    m_vacuum = geom.matter.Mixture("Vacuum", density = "1.e-25g/cc",
						components = (("videRef", 1.0),))

    m_aluminum_al = geom.matter.Mixture("ALUMINIUM_Al", density = "2.6990g/cc",
						components = (("aluminum", 1.0000),))

    m_silicon_si = geom.matter.Mixture("SILICON_Si", density = "2.3300g/cc",
						components = (("silicon", 1.0000),))

    m_epoxy_resin = geom.matter.Molecule("epoxy_resin", density = "1.1250g/cc",
						elements = (("carbon", 38),
									("hydrogen", 40),
									("oxygen", 6),
									("bromine", 4)))

    m_sio2 = geom.matter.Molecule("SiO2", density = "2.2g/cc",
						elements = (("silicon", 1),
									("oxygen", 2)))

    m_al2o3 = geom.matter.Molecule("Al2O3", density = "3.97g/cc",
						elements = (("aluminum", 2),
									("oxygen", 3)))

    m_fe2o3 = geom.matter.Molecule("Fe2O3", density = "5.24g/cc",
						elements = (("iron", 2),
									("oxygen", 3)))

    m_cao = geom.matter.Molecule("CaO", density = "3.35g/cc",
						elements = (("calcium", 1),
									("oxygen", 1)))

    m_delrin = geom.matter.Molecule("Delrin", density = "1.41g/cc",
						elements = (("carbon", 1),
									("hydrogen", 2),
									("oxygen", 1)))

    m_mgo = geom.matter.Molecule("MgO", density = "3.58g/cc",
						elements = (("magnesium", 1),
									("oxygen", 1)))

    m_na2o = geom.matter.Molecule("Na2O", density = "2.27g/cc",
						elements = (("sodium", 2),
									("oxygen", 1)))

    m_tio2 = geom.matter.Molecule("TiO2", density = "4.23g/cc",
						elements = (("titanium", 1),
									("oxygen", 2)))

    m_feo = geom.matter.Molecule("FeO", density = "5.745g/cc",
						elements = (("iron", 1),
									("oxygen", 1)))

    m_co2 = geom.matter.Molecule("CO2", density = "1.562g/cc",
						elements = (("iron", 1),
									("oxygen", 2)))

    m_p2o5 = geom.matter.Molecule("P2O5", density = "1.562g/cc",
						elements = (("phosphorus", 2),
									("oxygen", 5)))

    m_dusel_rock = geom.matter.Mixture("DUSEL_Rock", density = "2.82g/cc",
						components = (("SiO2", 0.5267),
									  ("FeO", 0.1174),
									  ("Al2O3", 0.1025),
									  ("MgO", 0.0473),
									  ("CO2", 0.0422),
									  ("CaO", 0.0382),
									  ("carbon", 0.0240),
									  ("sulphur", 0.0186),
									  ("Na2O", 0.0053),
									  ("P2O5", 0.00070),
									  ("oxygen", 0.0771)))

    m_air = geom.matter.Mixture("Air", density = "0.001205g/cc",
						components = (("nitrogen", 0.781154),
									  ("oxygen", 0.209476),
									  ("argon", 0.00934)))

    m_fibrous_glass = geom.matter.Mixture("fibrous_glass", density = "2.74351g/cc",
						components = (("SiO2", 0.600),
									  ("Al2O3", 0.118),
									  ("Fe2O3", 0.001),
									  ("CaO", 0.224),
									  ("MgO", 0.034),
									  ("Na2O", 0.010),
									  ("TiO2", 0.013)))

    m_fd_foam = geom.matter.Mixture("FD_foam", density = "0.09g/cc",
						components = (("Air", 0.95),
									  ("fibrous_glass", 0.05)))

    m_foam_protodune_rpuf_assayedsample = geom.matter.Molecule("foam_protoDUNE_RPUF_assayedSample", density = "0.09g/cc",
						elements = (("carbon", 54),
									("hydrogen", 60),
									("nitrogen", 4),
									("oxygen", 15)))

    m_foam_3x1x1dp = geom.matter.Mixture("foam_3x1x1dp", density = "0.07g/cc",
						components = (("Air", 0.95),
									  ("fibrous_glass", 0.05)))

    m_foam_protodunedp = geom.matter.Molecule("foam_protoDUNEdp", density = "0.135g/cc",
						elements = (("carbon", 17),
									("hydrogen", 16),
									("nitrogen", 2),
									("oxygen", 4)))

    m_fr4 = geom.matter.Mixture("FR4", density = "1.98281g/cc",
						components = (("epoxy_resin", 0.47),
									  ("fibrous_glass", 0.53)))

    m_fr4sussexapa = geom.matter.Mixture("FR4SussexAPA", density = "1.75g/cc",
						components = (("FR4", 1),))

    m_steel_stainless_fe7cr2ni = geom.matter.Mixture("STEEL_STAINLESS_Fe7Cr2Ni", density = "7.9300g/cc",
						components = (("carbon", 0.0010),
									  ("chromium", 0.1792),
									  ("iron", 0.7298),
									  ("nickel", 0.0900)))

    m_copper_beryllium_alloy25 = geom.matter.Mixture("Copper_Beryllium_alloy25", density = "8.26g/cc",
						components = (("copper", 0.981),
									  ("beryllium", 0.019)))

    m_lar = geom.matter.Mixture("LAr", density = "1.40g/cc",
						components = (("argon", 1.0000),))

    m_argas = geom.matter.Mixture("ArGas", density = "0.00166g/cc",
						components = (("argon", 1.0),))

    m_g10 = geom.matter.Mixture("G10", density = "1.7g/cc",
						components = (("silicon", 0.2805),
									  ("oxygen", 0.3954),
									  ("carbon", 0.2990),
									  ("hydrogen", 0.0251)))

    m_granite = geom.matter.Mixture("Granite", density = "2.7g/cc",
						components = (("oxygen", 0.438),
									  ("silicon", 0.257),
									  ("sodium", 0.222),
									  ("aluminum", 0.049),
									  ("iron", 0.019),
									  ("potassium", 0.015)))

    m_shotrock = geom.matter.Mixture("ShotRock", density = "1.62g/cc",
						components = (("oxygen", 0.438),
									  ("silicon", 0.257),
									  ("sodium", 0.222),
									  ("aluminum", 0.049),
									  ("iron", 0.019),
									  ("potassium", 0.015)))

    m_dirt = geom.matter.Mixture("Dirt", density = "1.7g/cc",
						components = (("oxygen", 0.438),
									  ("silicon", 0.257),
									  ("sodium", 0.222),
									  ("aluminum", 0.049),
									  ("iron", 0.019),
									  ("potassium", 0.015)))

    m_concrete = geom.matter.Mixture("Concrete", density = "2.3g/cc",
						components = (("oxygen", 0.530),
									  ("silicon", 0.335),
									  ("calcium", 0.060),
									  ("sodium", 0.015),
									  ("iron", 0.020),
									  ("aluminum", 0.040)))

    m_water = geom.matter.Mixture("Water", density = "1.0g/cc",
						components = (("hydrogen", 0.1119),
									  ("oxygen", 0.8881)))

    m_titanium = geom.matter.Mixture("Titanium", density = "4.506g/cc",
						components = (("titanium", 1.),))

    m_tpb = geom.matter.Mixture("TPB", density = "1.40g/cc",
						components = (("argon", 1.0000),))

    m_glass = geom.matter.Mixture("Glass", density = "2.74351g/cc",
						components = (("SiO2", 0.600),
									  ("Al2O3", 0.118),
									  ("Fe2O3", 0.001),
									  ("CaO", 0.224),
									  ("MgO", 0.034),
									  ("Na2O", 0.010),
									  ("TiO2", 0.013)))

    m_acrylic = geom.matter.Mixture("Acrylic", density = "1.19g/cc",
						components = (("carbon", 0.600),
									  ("oxygen", 0.320),
									  ("hydrogen", 0.080)))

    m_nigas1atm80k = geom.matter.Mixture("NiGas1atm80K", density = "0.0039g/cc",
						components = (("nitrogen", 1.000),))

    m_nigas = geom.matter.Mixture("NiGas", density = "0.001165g/cc",
						components = (("nitrogen", 1.000),))

    m_polyurethanefoam = geom.matter.Molecule("PolyurethaneFoam", density = "0.088g/cc",
						elements = (("carbon", 17),
									("hydrogen", 16),
									("nitrogen", 2),
									("oxygen", 4)))

    m_protodunefoam = geom.matter.Molecule("ProtoDUNEFoam", density = "0.135g/cc",
						elements = (("carbon", 17),
									("hydrogen", 16),
									("nitrogen", 2),
									("oxygen", 4)))

    m_lightpolyurethanefoam = geom.matter.Molecule("LightPolyurethaneFoam", density = "0.009g/cc",
						elements = (("carbon", 17),
									("hydrogen", 16),
									("nitrogen", 2),
									("oxygen", 4)))

    m_protodunebwfoam = geom.matter.Molecule("ProtoDUNEBWFoam", density = "0.021g/cc",
						elements = (("carbon", 17),
									("hydrogen", 16),
									("nitrogen", 2),
									("oxygen", 4)))

    m_glasswool = geom.matter.Mixture("GlassWool", density = "0.035g/cc",
						components = (("SiO2", 0.65),
									  ("Al2O3", 0.09),
									  ("CaO", 0.07),
									  ("MgO", 0.03),
									  ("Na2O", 0.16)))

    m_polystyrene = geom.matter.Molecule("Polystyrene", density = "1.06g/cc",
						elements = (("carbon", 8),
									("hydrogen", 8)))

    m_airsteelmixture = geom.matter.Mixture("AirSteelMixture", density = "3.9656025g/cc",
						components = (("STEEL_STAINLESS_Fe7Cr2Ni", 0.5),
									  ("Air", 0.5)))

    m_vm2000 = geom.matter.Molecule("vm2000", density = "1.2g/cc",
						elements = (("carbon", 2),
									("hydrogen", 4)))

