from setuptools import setup


setup(name = 'duneggd',
      version = '0.0',
      description = 'DUNE Geometries generated by GGD',
      author = 'Pierre Lasorak',
      author_email = 'plasorak@fnal.gov',
      license = 'GPLv2',
      url = 'https://github.com/DUNE/duneggd',
      package_dir = {'':'python'},
      packages = ['duneggd', 'duneggd.larfd'],
      install_requires = [l for l in open("requirements.txt").readlines() if l.strip()],
      # implicitly depends on ROOT
)

